In [1]:
import numpy as np
from scipy.spatial.distance import euclidean as l2_dist

In [2]:
x, y = np.array([[1, 2], [6, 7], [11, -12]]), np.array([[1, 2], [6, 7]])
x, y = y, x

In [3]:
x2 = np.sum(x**2, axis=1, keepdims=True)
y2 = np.sum(y**2, axis=1)
xy = np.dot(x, y.T)
dist = np.sqrt(x2 - 2*xy + y2)

dist

array([[  0.        ,   7.07106781,  17.20465053],
       [  7.07106781,   0.        ,  19.6468827 ]])

In [4]:
np.array([[l2_dist(y_i, x_j) for y_i in y] for x_j in x])

array([[  0.        ,   7.07106781,  17.20465053],
       [  7.07106781,   0.        ,  19.6468827 ]])

In [5]:
np.array([np.sqrt(np.power(y - x_i, 2).sum(axis=1)) for x_i in x])

array([[  0.        ,   7.07106781,  17.20465053],
       [  7.07106781,   0.        ,  19.6468827 ]])

In [90]:
N, D, H, W = 1, 2, 5, 3
a = np.ones([N, D, H, W])

HH, WW = 3, 3
pad, stride = 1, 2

np.pad(a, [(0, 0), (0, 0), (pad, pad), (pad, pad)], mode='constant')

array([[[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]]])

In [91]:
result = a[0] * a[0]
print(result.shape)
result

(2, 5, 3)


array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [110]:
a = np.random.rand(3,2)
print(a)
print(np.max(a))

[[ 0.51725213  0.06417008]
 [ 0.52463757  0.22759785]
 [ 0.96824176  0.53287612]]
0.968241759285


In [114]:
np.zeros([2, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
from sympy import Matrix, Symbol
x11, x12, x21, x22, x31, x32 = Symbol('x11'), Symbol('x12'), Symbol('x21'), Symbol('x22'), Symbol('x31'), Symbol('x32')
y11, y12, y21, y22 = Symbol('y11'), Symbol('y12'), Symbol('y21'), Symbol('y22')

In [8]:
x, y = np.array([[x11, x12], [x21, x22], [x31, x32]]), np.array([[y11, y12], [y21, y22]])
x, y = y, x

x2 = np.sum(x**2, axis=1, keepdims=True)
y2 = np.sum(y**2, axis=1)
xy = np.dot(x, y.T)
dist = x2 - 2*xy + y2

In [9]:
dist

array([[x11**2 - 2*x11*y11 + x12**2 - 2*x12*y12 + y11**2 + y12**2,
        x21**2 - 2*x21*y11 + x22**2 - 2*x22*y12 + y11**2 + y12**2,
        x31**2 - 2*x31*y11 + x32**2 - 2*x32*y12 + y11**2 + y12**2],
       [x11**2 - 2*x11*y21 + x12**2 - 2*x12*y22 + y21**2 + y22**2,
        x21**2 - 2*x21*y21 + x22**2 - 2*x22*y22 + y21**2 + y22**2,
        x31**2 - 2*x31*y21 + x32**2 - 2*x32*y22 + y21**2 + y22**2]], dtype=object)

In [10]:
l = [1, 2, 3, 4, 5]
l_copy = l.copy()

print(l, l_copy)

del l_copy[1]

print(l, l_copy)

[1, 2, 3, 4, 5] [1, 2, 3, 4, 5]
[1, 2, 3, 4, 5] [1, 3, 4, 5]


In [16]:
for row in np.array([[11, 12], [21, 22]]):
    print(row.T)

[11 12]
[21 22]


In [30]:
np.sum(np.array([[11, 12], [21, 22]])*np.array([[11, 12], [21, 22]]))

1190

In [24]:
np.array([1, 2, 3, 4, 5])[np.newaxis]

array([[1, 2, 3, 4, 5]])

In [27]:
True+True+True

3

In [5]:
np.zeros((1,5))

array([[ 0.,  0.,  0.,  0.,  0.]])

In [17]:
x = [[[[1, 2, 3], [11, 22, 33]], [[111, 222, 333], [1111, 2222, 3333]]],
     [[[9, 8, 7], [9, 8, 7]], [[9, 8, 7], [9, 8, 7]]]]
x = np.array(x)

x_reshaped = x.reshape(x.shape[0], np.prod(x.shape[1:]))
w = np.array([range(12), range(12, 24), range(24, 36)]).T

print(x.shape, x_reshaped.shape, w.shape)

(2, 2, 2, 3) (2, 12) (12, 3)


In [10]:
np.dot(x_reshaped, w)

NameError: name 'x_reshaped' is not defined

In [22]:
np.dot(x_reshaped, w) + np. array([1, 0, -1])

array([[ 74061, 162908, 251755],
       [   521,   1672,   2823]])

In [23]:
p = 0.5
x = 5*np.ones([2, 3, 1])
mask = np.random.choice([0, 1], size=x.shape, p=[p, 1-p])

(x*mask)

array([[[ 0.],
        [ 5.],
        [ 5.]],

       [[ 5.],
        [ 0.],
        [ 0.]]])

In [1]:
556+841

1397